const italianToEnglishDictionary = [
  // Common Words (1-100)
  ["ciao", "hello/goodbye"],
  ["grazie", "thank you"],
  ["prego", "you're welcome"],
  ["sì", "yes"],
  ["no", "no"],
  ["per favore", "please"],
  ["scusa", "excuse me/sorry"],
  ["buongiorno", "good morning"],
  ["buonasera", "good evening"],
  ["buonanotte", "good night"],
  ["arrivederci", "goodbye"],
  ["come", "how"],
  ["che", "what"],
  ["dove", "where"],
  ["quando", "when"],
  ["perché", "why"],
  ["chi", "who"],
  ["quale", "which"],
  ["quanto", "how much"],
  ["bene", "well"],
  ["male", "bad"],
  ["qui", "here"],
  ["là", "there"],
  ["oggi", "today"],
  ["domani", "tomorrow"],
  ["ieri", "yesterday"],
  ["adesso", "now"],
  ["poi", "then"],
  ["sempre", "always"],
  ["mai", "never"],
  ["spesso", "often"],
  ["qualche volta", "sometimes"],
  ["ancora", "still/yet"],
  ["già", "already"],
  ["subito", "immediately"],
  ["dopo", "after"],
  ["prima", "before"],
  ["con", "with"],
  ["senza", "without"],
  ["su", "on"],
  ["sotto", "under"],
  ["in", "in"],
  ["a", "to/at"],
  ["da", "from/by"],
  ["per", "for"],
  ["tra/fra", "between/among"],
  ["di", "of"],
  ["e", "and"],
  ["ma", "but"],
  ["o", "or"],
  ["se", "if"],
  ["perché", "because"],
  ["come", "as/like"],
  ["mentre", "while"],
  ["quindi", "so/therefore"],
  ["molto", "very"],
  ["troppo", "too much"],
  ["poco", "little"],
  ["tanto", "so much"],
  ["altro", "other"],
  ["stesso", "same"],
  ["tutto", "all/everything"],
  ["niente", "nothing"],
  ["qualcosa", "something"],
  ["qualcuno", "someone"],
  ["ogni", "each/every"],
  ["alcuni", "some"],
  ["nessuno", "no one/none"],
  ["io", "I"],
  ["tu", "you"],
  ["lui", "he"],
  ["lei", "she"],
  ["noi", "we"],
  ["voi", "you"],
  ["loro", "they"],
  ["mio", "my"],
  ["tuo", "your"],
  ["suo", "his/her"],
  ["nostro", "our"],
  ["vostro", "your"],
  ["loro", "their"],
  ["questo", "this"],
  ["quello", "that"],
  ["cosa", "thing"],
  ["persona", "person"],
  ["posto", "place"],
  ["tempo", "time/weather"],
  ["anno", "year"],
  ["mese", "month"],
  ["settimana", "week"],
  ["giorno", "day"],
  ["ora", "hour/now"],
  ["minuto", "minute"],
  ["secondo", "second"],
  ["uomo", "man"],
  ["donna", "woman"],
  ["bambino", "child"],
  ["ragazzo", "boy"],
  ["ragazza", "girl"],

  // Family & People (101-150)
  ["famiglia", "family"],
  ["padre", "father"],
  ["madre", "mother"],
  ["genitori", "parents"],
  ["figlio", "son"],
  ["figlia", "daughter"],
  ["fratello", "brother"],
  ["sorella", "sister"],
  ["marito", "husband"],
  ["moglie", "wife"],
  ["zio", "uncle"],
  ["zia", "aunt"],
  ["nonno", "grandfather"],
  ["nonna", "grandmother"],
  ["nipote", "grandchild/nephew/niece"],
  ["cugino", "cousin"],
  ["amico", "friend (male)"],
  ["amica", "friend (female)"],
  ["vicino", "neighbor"],
  ["collega", "colleague"],
  ["capo", "boss"],
  ["insegnante", "teacher"],
  ["studente", "student"],
  ["dottore", "doctor"],
  ["infermiere", "nurse"],
  ["poliziotto", "police officer"],
  ["cuoco", "cook/chef"],
  ["cameriere", "waiter"],
  ["avvocato", "lawyer"],
  ["ingegnere", "engineer"],
  ["artista", "artist"],
  ["scrittore", "writer"],
  ["musico", "musician"],
  ["attore", "actor"],
  ["attrice", "actress"],
  ["cantante", "singer"],
  ["ballerino", "dancer"],
  ["pittore", "painter"],
  ["giornalista", "journalist"],

  // Food & Drink (151-220)
  ["cibo", "food"],
  ["acqua", "water"],
  ["pane", "bread"],
  ["pasta", "pasta"],
  ["riso", "rice"],
  ["carne", "meat"],
  ["pollo", "chicken"],
  ["manzo", "beef"],
  ["maiale", "pork"],
  ["pesce", "fish"],
  ["frutta", "fruit"],
  ["verdura", "vegetables"],
  ["insalata", "salad"],
  ["patate", "potatoes"],
  ["pomodoro", "tomato"],
  ["formaggio", "cheese"],
  ["uovo", "egg"],
  ["burro", "butter"],
  ["olio", "oil"],
  ["sale", "salt"],
  ["pepe", "pepper"],
  ["zucchero", "sugar"],
  ["caffè", "coffee"],
  ["tè", "tea"],
  ["latte", "milk"],
  ["vino", "wine"],
  ["birra", "beer"],
  ["succo", "juice"],
  ["pizza", "pizza"],
  ["gelato", "ice cream"],
  ["torta", "cake"],
  ["cioccolato", "chocolate"],
  ["biscotto", "cookie"],
  ["colazione", "breakfast"],
  ["pranzo", "lunch"],
  ["cena", "dinner"],
  ["spuntino", "snack"],
  ["ristorante", "restaurant"],
  ["cucina", "kitchen/cuisine"],
  ["piatto", "plate/dish"],
  ["forchetta", "fork"],
  ["coltello", "knife"],
  ["cucchiaio", "spoon"],
  ["bicchiere", "glass"],
  ["tazza", "cup"],
  ["bottiglia", "bottle"],

  // House & Objects (221-300)
  ["casa", "house/home"],
  ["appartamento", "apartment"],
  ["stanza", "room"],
  ["camera", "bedroom"],
  ["cucina", "kitchen"],
  ["bagno", "bathroom"],
  ["soggiorno", "living room"],
  ["scala", "stairs"],
  ["porta", "door"],
  ["finestra", "window"],
  ["tavolo", "table"],
  ["sedia", "chair"],
  ["letto", "bed"],
  ["armadio", "wardrobe"],
  ["divano", "sofa"],
  ["televisore", "television"],
  ["computer", "computer"],
  ["telefono", "telephone"],
  ["libro", "book"],
  ["giornale", "newspaper"],
  ["penna", "pen"],
  ["matita", "pencil"],
  ["carta", "paper"],
  ["chiave", "key"],
  ["orologio", "watch/clock"],
  ["specchio", "mirror"],
  ["lampada", "lamp"],
  ["pavimento", "floor"],
  ["soffitto", "ceiling"],
  ["parete", "wall"],
  ["giardino", "garden"],
  ["garage", "garage"],
  ["balcone", "balcony"],
  ["ascensore", "elevator"],

  // City & Places (301-350)
  ["città", "city"],
  ["paese", "town/village"],
  ["strada", "street"],
  ["piazza", "square"],
  ["parco", "park"],
  ["negozio", "shop"],
  ["supermercato", "supermarket"],
  ["mercato", "market"],
  ["banca", "bank"],
  ["posto", "post office"],
  ["ospedale", "hospital"],
  ["farmacia", "pharmacy"],
  ["scuola", "school"],
  ["università", "university"],
  ["biblioteca", "library"],
  ["museo", "museum"],
  ["cinema", "cinema"],
  ["teatro", "theater"],
  ["albergo", "hotel"],
  ["spiaggia", "beach"],
  ["montagna", "mountain"],
  ["lago", "lake"],
  ["fiume", "river"],
  ["mare", "sea"],
  ["isola", "island"],
  ["bosco", "forest"],
  ["campagna", "countryside"],

  // Transportation (351-400)
  ["macchina", "car"],
  ["autobus", "bus"],
  ["treno", "train"],
  ["aereo", "airplane"],
  ["nave", "ship"],
  ["bicicletta", "bicycle"],
  ["moto", "motorcycle"],
  ["taxi", "taxi"],
  ["stazione", "station"],
  ["aeroporto", "airport"],
  ["porto", "port"],
  ["biglietto", "ticket"],
  ["valigia", "suitcase"],
  ["viaggio", "trip"],
  ["vacanza", "vacation"],
  ["destinazione", "destination"],
  ["partenza", "departure"],
  ["arrivo", "arrival"],

  // Work & Education (401-450)
  ["lavoro", "work/job"],
  ["ufficio", "office"],
  ["riunione", "meeting"],
  ["progetto", "project"],
  ["dovere", "duty"],
  ["compito", "task"],
  ["studio", "study"],
  ["esame", "exam"],
  ["voto", "grade"],
  ["classe", "class"],
  ["lezione", "lesson"],
  ["compiti", "homework"],
  ["penna", "pen"],
  ["quaderno", "notebook"],
  ["calcolatrice", "calculator"],
  ["scienza", "science"],
  ["matematica", "math"],
  ["storia", "history"],
  ["geografia", "geography"],
  ["arte", "art"],
  ["musica", "music"],

  // Body & Health (451-500)
  ["corpo", "body"],
  ["testa", "head"],
  ["occhio", "eye"],
  ["orecchio", "ear"],
  ["naso", "nose"],
  ["bocca", "mouth"],
  ["dente", "tooth"],
  ["lingua", "tongue"],
  ["capello", "hair"],
  ["faccia", "face"],
  ["mano", "hand"],
  ["piede", "foot"],
  ["braccio", "arm"],
  ["gamba", "leg"],
  ["cuore", "heart"],
  ["polmone", "lung"],
  ["salute", "health"],
  ["malattia", "illness"],
  ["febbre", "fever"],
  ["dolore", "pain"],
  ["medicina", "medicine"],
  ["dottore", "doctor"],
  ["infermiere", "nurse"],
  ["ospedale", "hospital"],

  // Clothing (501-550)
  ["vestiti", "clothes"],
  ["camicia", "shirt"],
  ["pantaloni", "pants/trousers"],
  ["gonna", "skirt"],
  ["vestito", "dress"],
  ["cappotto", "coat"],
  ["scarpe", "shoes"],
  ["stivali", "boots"],
  ["cappello", "hat"],
  ["guanti", "gloves"],
  ["sciarpa", "scarf"],
  ["calzini", "socks"],
  ["biancheria intima", "underwear"],
  ["pigiama", "pajamas"],
  ["costume da bagno", "swimsuit"],

  // Colors (551-580)
  ["colore", "color"],
  ["rosso", "red"],
  ["blu", "blue"],
  ["verde", "green"],
  ["giallo", "yellow"],
  ["nero", "black"],
  ["bianco", "white"],
  ["grigio", "gray"],
  ["marrone", "brown"],
  ["arancione", "orange"],
  ["viola", "purple"],
  ["rosa", "pink"],
  ["azzurro", "light blue"],

  // Animals (581-630)
  ["animale", "animal"],
  ["cane", "dog"],
  ["gatto", "cat"],
  ["cavallo", "horse"],
  ["mucca", "cow"],
  ["maiale", "pig"],
  ["pecora", "sheep"],
  ["capra", "goat"],
  ["gallina", "hen"],
  ["uccello", "bird"],
  ["pesce", "fish"],
  ["serpente", "snake"],
  ["topo", "mouse"],
  ["leone", "lion"],
  ["tigre", "tiger"],
  ["orso", "bear"],
  ["elefante", "elephant"],
  ["scimmia", "monkey"],
  ["coccodrillo", "crocodile"],

  // Weather & Nature (631-680)
  ["tempo", "weather"],
  ["sole", "sun"],
  ["luna", "moon"],
  ["stella", "star"],
  ["cielo", "sky"],
  ["nube", "cloud"],
  ["pioggia", "rain"],
  ["neve", "snow"],
  ["vento", "wind"],
  ["tempesta", "storm"],
  ["caldo", "hot"],
  ["freddo", "cold"],
  ["caldo", "warm"],
  ["fresco", "cool"],
  ["albero", "tree"],
  ["fiore", "flower"],
  ["erba", "grass"],
  ["pietra", "stone"],
  ["terra", "earth/ground"],
  ["sabbia", "sand"],
  ["ghiaccio", "ice"],

  // Verbs (681-730) - Infinitives
  ["essere", "to be"],
  ["avere", "to have"],
  ["fare", "to do/make"],
  ["dire", "to say"],
  ["andare", "to go"],
  ["venire", "to come"],
  ["potere", "to be able to/can"],
  ["volere", "to want"],
  ["dovere", "to have to/must"],
  ["vedere", "to see"],
  ["sentire", "to hear"],
  ["parlare", "to speak"],
  ["mangiare", "to eat"],
  ["bere", "to drink"],
  ["dormire", "to sleep"],
  ["svegliarsi", "to wake up"],
  ["lavorare", "to work"],
  ["studiare", "to study"],
  ["leggere", "to read"],
  ["scrivere", "to write"],
  ["capire", "to understand"],
  ["sapere", "to know"],
  ["conoscere", "to know/meet"],
  ["pensare", "to think"],
  ["credere", "to believe"],
  ["trovare", "to find"],
  ["prendere", "to take"],
  ["dare", "to give"],
  ["mettere", "to put"],
  ["stare", "to stay/be"],
  ["uscire", "to go out"],
  ["entrare", "to enter"],
  ["tornare", "to return"],
  ["cominciare", "to begin"],
  ["finire", "to finish"],
  ["aspettare", "to wait"],
  ["chiamare", "to call"],
  ["guardare", "to watch/look"],
  ["cercare", "to search/look for"],
  ["comprare", "to buy"],
  ["vendere", "to sell"],
  ["pagare", "to pay"],
  ["costare", "to cost"],
  ["aprire", "to open"],
  ["chiudere", "to close"],
  ["camminare", "to walk"],
  ["correre", "to run"],
  ["saltare", "to jump"],
  ["volare", "to fly"],
  ["nuotare", "to swim"],

  // Adjectives (731-780)
  ["grande", "big/large"],
  ["piccolo", "small"],
  ["alto", "tall/high"],
  ["basso", "short/low"],
  ["lungo", "long"],
  ["corto", "short"],
  ["largo", "wide"],
  ["stretto", "narrow"],
  ["nuovo", "new"],
  ["vecchio", "old"],
  ["giovane", "young"],
  ["bello", "beautiful"],
  ["brutto", "ugly"],
  ["buono", "good"],
  ["cattivo", "bad"],
  ["facile", "easy"],
  ["difficile", "difficult"],
  ["forte", "strong"],
  ["debole", "weak"],
  ["veloce", "fast"],
  ["lento", "slow"],
  ["pesante", "heavy"],
  ["leggero", "light"],
  ["duro", "hard"],
  ["morbido", "soft"],
  ["caldo", "hot/warm"],
  ["freddo", "cold"],
  ["pieno", "full"],
  ["vuoto", "empty"],
  ["ricco", "rich"],
  ["povero", "poor"],
  ["felice", "happy"],
  ["triste", "sad"],
  ["nervoso", "nervous"],
  ["calmo", "calm"],
  ["occupato", "busy"],
  ["libero", "free"],
  ["pulito", "clean"],
  ["sporco", "dirty"],
  ["chiaro", "clear/light"],
  ["scuro", "dark"],
  ["sicuro", "safe/sure"],
  ["pericoloso", "dangerous"],
  ["importante", "important"],
  ["interessante", "interesting"],
  ["noioso", "boring"],
  ["divertente", "funny/entertaining"],

  // Numbers (781-800)
  ["zero", "zero"],
  ["uno", "one"],
  ["due", "two"],
  ["tre", "three"],
  ["quattro", "four"],
  ["cinque", "five"],
  ["sei", "six"],
  ["sette", "seven"],
  ["otto", "eight"],
  ["nove", "nine"],
  ["dieci", "ten"],
  ["cento", "one hundred"],
  ["mille", "one thousand"],
  ["milione", "million"],

  // Time & Dates (801-850)
  ["data", "date"],
  ["giorno", "day"],
  ["notte", "night"],
  ["mattina", "morning"],
  ["pomeriggio", "afternoon"],
  ["sera", "evening"],
  ["mezzogiorno", "noon"],
  ["mezzanotte", "midnight"],
  ["lunedì", "Monday"],
  ["martedì", "Tuesday"],
  ["mercoledì", "Wednesday"],
  ["giovedì", "Thursday"],
  ["venerdì", "Friday"],
  ["sabato", "Saturday"],
  ["domenica", "Sunday"],
  ["gennaio", "January"],
  ["febbraio", "February"],
  ["marzo", "March"],
  ["aprile", "April"],
  ["maggio", "May"],
  ["giugno", "June"],
  ["luglio", "July"],
  ["agosto", "August"],
  ["settembre", "September"],
  ["ottobre", "October"],
  ["novembre", "November"],
  ["dicembre", "December"],
  ["primavera", "spring"],
  ["estate", "summer"],
  ["autunno", "autumn"],
  ["inverno", "winter"],

  // Miscellaneous (851-900+)
  ["problema", "problem"],
  ["soluzione", "solution"],
  ["idea", "idea"],
  ["pensiero", "thought"],
  ["sogno", "dream"],
  ["realtà", "reality"],
  ["verità", "truth"],
  ["bugia", "lie"],
  ["segreto", "secret"],
  ["notizia", "news"],
  ["informazione", "information"],
  ["domanda", "question"],
  ["risposta", "answer"],
  ["possibilità", "possibility"],
  ["occasione", "opportunity"],
  ["cambiamento", "change"],
  ["scelta", "choice"],
  ["decisione", "decision"],
  ["ragione", "reason"],
  ["risultato", "result"],
  ["successo", "success"],
  ["fallimento", "failure"],
  ["esperienza", "experience"],
  ["memoria", "memory"],
  ["futuro", "future"],
  ["passato", "past"],
  ["presente", "present"],
  ["momento", "moment"],
  ["situazione", "situation"],
  ["condizione", "condition"],
  ["stato", "state"],
  ["governo", "government"],
  ["politica", "politics"],
  ["economia", "economy"],
  ["società", "society"],
  ["cultura", "culture"],
  ["religione", "religion"],
  ["arte", "art"],
  ["scienza", "science"],
  ["tecnologia", "technology"],
  ["sviluppo", "development"],
  ["progresso", "progress"],
  ["ambiente", "environment"],
  ["natura", "nature"],
  ["mondo", "world"],
  ["pace", "peace"],
  ["guerra", "war"],
  ["libertà", "freedom"],
  ["giustizia", "justice"],
  ["diritto", "right/law"],
  ["dovere", "duty"],
  ["amore", "love"],
  ["odio", "hate"],
  ["paura", "fear"],
  ["coraggio", "courage"],
  ["speranza", "hope"],
  ["fede", "faith"],
  ["fortuna", "luck"],
  ["caso", "case/chance"]
];

module.exports = italianToEnglishDictionary;

